mis_cosas/mis_cosas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web_mis_cosas.urls')),
]

mis_cosas/web_mis_cosas/urls.py
from django.urls import path
from django.contrib.auth import views as views_login
from . import views

urlpatterns = [
    path('', views.principal_page, name='principal_page'),
    path('item/', views.item_page, name='item_page'),
    path('item/<str:id_vid>', views.item_page, name='item_page'),
    path('registrarse/', views.registrarse_page, name='registrarse_page'),
    path('post/new/', views.post_new, name='post_new'),
    path('informacion/', views.informacion_page, name='informacion_page'),
    path('alimentadores/', views.alimentadores, name='alimentadores'),
    path('alimentadores/<str:alim_id>', views.alimentador_info, name='alimentador_info'),
#    path('alimentadores/', views.alimentadores_page, name='alimentadores_page'),
    path('usuarios/', views.usuarios_page, name='usuarios_page'),
    path('usuarios/<str:uname>', views.usuario_page, name='usuario_page'),
    path('colores', views.colores, name='colores'),
#    path('login', views_login.LoginView.as_view(), name='login_user'),
    path('login', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
]

mis_cosas/web_mis_cosas/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title



class Alimentador(models.Model):
    id_canal = models.CharField(max_length=256)
    titulo = models.CharField(max_length=64)
    enlace = models.URLField()
    votos_pos = models.IntegerField(default=0)
    votos_neg = models.IntegerField(default=0)
    puntuacion = models.IntegerField(default=0)
    elegido = models.BooleanField(default=True)

    def __str__(self):
        return self.id_canal



class Item(models.Model):
    alimentador = models.ForeignKey(Alimentador, on_delete=models.CASCADE)
    id_video = models.CharField(max_length=256)
    titulo = models.CharField(max_length=64)
    enlace = models.URLField()
    descripcion = models.CharField(max_length=512)
    video = models.CharField(max_length=256)
    votos_pos = models.IntegerField(default=0)
    votos_neg = models.IntegerField(default=0)
    tipo = models.CharField(max_length=10, default="youtube")

    def __str__(self):
        return self.titulo + "|" + self.id_video



class Usuario(models.Model):
    username = models.CharField(max_length=100, default="ejemplo")
    password = models.CharField(max_length=50, default="ejemplo")
    email = models.EmailField(max_length=100, default="ejemplo@ejemplo.com")
    items = models.ManyToManyField(Item, blank=True, null=True)
    titulo = models.CharField(max_length=300, default="Pagina del usuario")
    nvotos = models.PositiveSmallIntegerField(default=0)
    ncomentarios = models.PositiveSmallIntegerField(default=0)
    bg_color = models.CharField(max_length=20, default="white")
    letras_size = models.IntegerField(default="100")

    def __str__(self):
        return self.username


class Comentario(models.Model):
    autor = models.ForeignKey(Usuario, on_delete=models.CASCADE, blank=True, null=True)
    texto = models.TextField()
    item = models.ForeignKey(Item, on_delete=models.CASCADE, blank=True, null=True)


    def __str__(self):
        return self.texto


class Voto(models.Model):
    autor = models.ForeignKey(Usuario, on_delete=models.CASCADE, blank=True, null=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, blank=True, null=True)
    tipo = models.CharField(max_length=10, default="Positivo")

    def __str__(self):
        return "voto"

mis_cosas/web_mis_cosas/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class LoginForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


#class YoutubeForm(forms.ModelForm):
#    class Meta:
#        model = Alimentador
#        fields = ('id_canal')

mis_cosas/web_mis_cosas/views.py
from django.shortcuts import render
from django.utils import timezone
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth import login, logout, authenticate, get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as do_login
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.template.loader import get_template

from urllib.request import urlopen

from .models import Post, Alimentador, Item, Usuario, Comentario, Voto
from .forms import PostForm, LoginForm, UserForm #, YoutubeForm
from .yt import YTChannel
from .wk import WikiArticle

import urllib



def principal_page(request):



    if request.method == "GET":

       #Lista de 10 items mas votados
        lista_items = []
        items = Item.objects.all()
        for item in items:
            puntuacion = item.votos_pos - item.votos_neg
            if len(lista_items) < 10:
                lista_items.append(item)
            else:
                caja = item
                n = 0
                for e in lista_items:
                    e_puntuacion = e.votos_pos - e.votos_neg
                    if e_puntuacion < puntuacion:
                        tmp = lista_items[n]
                        lista_items[n] = caja
                        caja = tmp
                    n = n + 1

        posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
        form = AuthenticationForm()
        lista_alimentadores = Alimentador.objects.all()

        lista_votos = []
        usuario = request.user.username
        if usuario:
            usuario = Usuario.objects.get(username=usuario)
            lista_votos = Voto.objects.all().filter(autor=usuario)
        #    print(lista_votos.count())
            if lista_votos.count() > 5:
                lista_votos = lista_votos[::-1]
                lista_votos = lista_votos[0:5]

        formato = request.GET.get('format')
        if formato and formato == 'xml':
            return render(request, 'blog/principal.xml', {'form': form, 'lista_items':lista_items, 'lista_alimentadores':lista_alimentadores, 'lista_votos':lista_votos, 'usuario':usuario}, content_type="application/xml")
        elif formato and formato == 'json':
            return render(request, 'blog/principal.json', {'form': form, 'lista_items':lista_items, 'lista_alimentadores':lista_alimentadores, 'lista_votos':lista_votos, 'usuario':usuario}, content_type="application/json")
        else:
            return render(request, 'blog/principal.html', {'form': form, 'lista_items':lista_items, 'lista_alimentadores':lista_alimentadores, 'lista_votos':lista_votos, 'usuario':usuario})

    else:
        id_or_name = request.POST['valor']

        if not id_or_name or id_or_name[0] == " ":
            return render(request, 'blog/void.html')
        else:

            action = request.POST['action']

            if action == "VER_YT":
                xmlStream = urlopen('https://www.youtube.com/feeds/videos.xml?channel_id=' + id_or_name)
                link = ('https://www.youtube.com/channel/' + id_or_name)
                channel = YTChannel(xmlStream)

                try:
                    alimentador = Alimentador.objects.get(enlace=channel.uriAlim())
                except Alimentador.DoesNotExist:
                    alimentador = Alimentador(titulo= channel.nameAlim(),
                                  enlace=channel.uriAlim(), id_canal = id_or_name)
                    alimentador.save()

                for video in channel.videos():
                    video = Item(alimentador = alimentador, titulo=video['title'],
                                  enlace=video['link'], descripcion = video['description'], id_video = video['id'], tipo = "youtube")
                    video.save()

            if action == "VER_WK":
                xmlStream = urlopen('https://es.wikipedia.org/w/index.php?title=' + id_or_name + '&action=history&feed=rss')
                link = ('https://es.wikipedia.org/wiki/' + id_or_name)
                articulo = WikiArticle(xmlStream)

                try:
                    alimentador = Alimentador.objects.get(titulo=articulo.arttitle())
                except Alimentador.DoesNotExist:
                    alimentador = Alimentador(titulo = articulo.arttitle(), enlace = articulo.artlink(), id_canal = articulo.arttitle())
                    alimentador.save()


                for cambio in articulo.cambios():
                    n = cambio['link_cambio'].find("index.php?") + 10
                    cambio_id = cambio['link_cambio'][n:]
                    tit = cambio['title'] + " | " + cambio['link_cambio'][n:]
                    print(tit)

                    cambio = Item(alimentador = alimentador, titulo=tit,
                                  enlace=cambio['link_cambio'], descripcion = cambio['comments'], id_video = cambio_id, tipo = "wikipedia")

                    cambio.save()


#Ahora muestra todos los alimentadores pero tendrá que mostrar los que correspondad (Youtube o Wikipedia)
        lista_alimentadores = Alimentador.objects.all()
        contexto = {'lista_alimentadores': lista_alimentadores}
        return render(request, 'blog/alimentadores.html', contexto)


def alimentadores(request):
    lista_alimentadores = Alimentador.objects.all()
    usuario = request.user.username
    if usuario:
        usuario = Usuario.objects.get(username=usuario)


    return render(request, 'blog/alimentadores.html', {'lista_alimentadores': lista_alimentadores, 'usuario': usuario})


def alimentador_info(request, alim_id):
    try:
        alimentador = Alimentador.objects.get(id_canal = alim_id)
    except Alimentador.DoesNotExist:
        return render(request, 'blog/void.html')

    if request.method == "POST":
        elegir = request.POST.get('elegir', False)

        if elegir == "Eliminar":
            alimentador.elegido = False
            alimentador.save()

        if elegir == "Elegir":
            alimentador.elegido = True
            alimentador.save()

    usuario = request.user.username
    if usuario:
        usuario = Usuario.objects.get(username=usuario)


    context = {'alimentador': alimentador, 'usuario': usuario}
    return render(request, 'blog/alimentador.html', context)


def item_page(request, id_vid):

    item = Item.objects.get(id_video = id_vid)
    alimentador = item.alimentador
    usuario = request.user.username
    if usuario:
        usuario = Usuario.objects.get(username=usuario)


    if request.method == "POST":
        action = request.POST.get('action', False)
        voto = request.POST.get('voto', False)

        lista_items_votados = Voto.objects.all().filter(autor=usuario)


        if action == "Comentar":
            texto_comentario = request.POST['valor']
            autor_comentario = request.user.username
            autor_comentario = Usuario.objects.get(username=autor_comentario)
            item_comentado = Item.objects.get(id_video = id_vid)
            comentario = Comentario(autor = autor_comentario, texto = texto_comentario, item = item_comentado)
            comentario.save()

        elif voto == "( + )":
            if not lista_items_votados.filter(item = item).exists():
                item.votos_pos = item.votos_pos + 1
                alimentador.votos_pos = alimentador.votos_pos + 1
                alimentador.puntuacion = alimentador.puntuacion + 1
                item.save()
                alimentador.save()

                autor_voto = request.user.username
                autor_voto = Usuario.objects.get(username=autor_voto)
                item_votado = Item.objects.get(id_video = id_vid)
                new_voto = Voto(autor = autor_voto, item = item_votado, tipo = "Positivo")
                new_voto.save()
            else:
                autor_voto = request.user.username
                autor_voto = Usuario.objects.get(username=autor_voto)
                item_votado = Item.objects.get(id_video = id_vid)
                votos = Voto.objects.filter(autor = autor_voto)
                for v in votos:
                    if v.item == item_votado and v.tipo == "Negativo":
                        v.tipo = "Positivo"
                        v.save()

                        item.votos_neg = item.votos_neg - 1
                        item.votos_pos = item.votos_pos + 1
                        alimentador.votos_neg = alimentador.votos_neg - 1
                        alimentador.votos_pos = alimentador.votos_pos + 1
                        alimentador.puntuacion = alimentador.puntuacion + 2
                        item.save()
                        alimentador.save()


                print("AHORA###################")


        elif voto == "( - )":
            if not lista_items_votados.filter(item = item).exists():
                item.votos_neg = item.votos_neg + 1
                alimentador.votos_neg = alimentador.votos_neg + 1
                alimentador.puntuacion = alimentador.puntuacion - 1
                item.save()
                alimentador.save()

                autor_voto = request.user.username
                autor_voto = Usuario.objects.get(username=autor_voto)
                item_votado = Item.objects.get(id_video = id_vid)
                new_voto = Voto(autor = autor_voto, item = item_votado, tipo = "Negativo")
                new_voto.save()


            else:
                autor_voto = request.user.username
                autor_voto = Usuario.objects.get(username=autor_voto)
                item_votado = Item.objects.get(id_video = id_vid)
                votos = Voto.objects.filter(autor = autor_voto)
                for v in votos:
                    if v.item == item_votado and v.tipo == "Positivo":
                        v.tipo = "Negativo"

mis_cosas/web_mis_cosas/templates/blog/alimentador.html
{% extends 'blog/base.html' %}


{% block content %}


<br>
<h2>Alimentador: {{ alimentador.titulo }}</h2>
<br>
Link: <a href="{{ alimentador.enlace }}">{{ alimentador.enlace }}</a>
<br>
Numero de items disponibles: {{alimentador.item_set.count}}
<br>

{% if alimentador.elegido == True %}
                 <form action="/alimentadores/{{alimentador.id_canal}}" method="POST">{% csrf_token %}
                          <th><input type="submit" name="elegir" value="Eliminar"></th>
                 </form>
{% else %}
                 <form action="/alimentadores/{{alimentador.id_canal}}" method="POST">{% csrf_token %}
                          <th><input type="submit" name="elegir" value="Elegir"></th>
                 </form>
{% endif %}

<br>
Lista de items:
<br>
            {% for item in alimentador.item_set.all %}
                <li><a href="/item/{{ item.id_video  }}">{{ item.titulo }}</a>
                <ul>Link: <a href="{{ item.enlace }}">{{ item.enlace }}</a></ul></li>
            {% endfor %}


{% endblock %}

mis_cosas/web_mis_cosas/templates/blog/alimentadores.html
{% extends 'blog/base.html' %}


{% block content %}

{% if lista_alimentadores %}

<h3>Lista de alimentadores</h3>

        <table>
                        <tr>
                                <th>Alimentador</th>
                                <th>Link</th>
                                <th>Items disponibles</th>
                                <th>Puntuación</th>
                        </tr>

    {% for alimentador in lista_alimentadores %}
        <tr>
                <th><a href="{% url 'alimentador_info' alim_id=alimentador.id_canal%}">{{ alimentador.titulo }}</th>
                <th><a href="{{ alimentador.enlace }}">{{ alimentador.enlace }}</a></th>
                <th>{{alimentador.item_set.count}}</th>
                <th>{{alimentador.puntuacion}}</th>
        </tr>
    {% endfor %}
    </table>

{% else %}
    <p>Todavía no hay canales registrados</p>
{% endif %}

<!--
    {% for post in posts %}
        <div class="post">
            <div class="date">
                {{ post.published_date }}
            </div>
            <h2><a href="">{{ post.title }}</a></h2>
            <p>{{ post.text|linebreaksbr }}</p>
        </div>
    {% endfor %}
-->

{% endblock %}

mis_cosas/web_mis_cosas/templates/blog/base.html
{% load static %}
<html>
<head>
	<meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" type="image/png" href="https://image.flaticon.com/icons/svg/2927/2927929.svg"/>
	<title>web_mis_cosas</title>
<style>

table {
  border-collapse: collapse;
  border-spacing: 0;
  width: 100%;
  border: 1px solid #ddd;
}

th, td {
  text-align: left;
  padding: 16px;
}

tr:nth-child(even) {
  background-color: #f2f2f2;
}

body {font-family: Arial, Helvetica, sans-serif;}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

/* Set a style for all buttons */
button {
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

button:hover {
  opacity: 0.8;
}

/* Extra styles for the cancel button */
.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: #f44336;
}

/* Center the image and position the close button */
.imgcontainer {
  text-align: center;
  margin: 24px 0 12px 0;
  position: relative;
}

img.avatar {
  width: 20%;
  border-radius: 50%;
}

.container {
  padding: 16px;
}

span.psw {
  float: right;
  padding-top: 16px;
}

/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
  padding-top: 60px;
}

/* Modal Content/Box */
.modal-content {
  background-color: #fefefe;
  margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
  border: 1px solid #888;
  width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button (x) */
.close {
  position: absolute;
  right: 25px;
  top: 0;
  color: #000;
  font-size: 35px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: red;
  cursor: pointer;
}

/* Add Zoom Animation */
.animate {
  -webkit-animation: animatezoom 0.6s;
  animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
  from {-webkit-transform: scale(0)} 
  to {-webkit-transform: scale(1)}
}
  
@keyframes animatezoom {
  from {transform: scale(0)} 
  to {transform: scale(1)}
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
  span.psw {
     display: block;
     float: none;
  }
  .cancelbtn {
     width: 100%;
  }
}
</style>

<style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #4CAF50;
  color: white;
}
</style>

</head>
{% if user.is_authenticated  %}
<body style="background-color:{{ usuario.bg_color  }};">
{% else %}
<body>
{% endif %}

<!--
    <div class="page-header">
        <h1><a href="/">MIS COSAS</a></h1>
    </div>
-->

<div class="topnav">
                <a class="active" href="/">Principal</a>
                <a href="/usuarios/{{user.username}}">Personal</a>
                <a href="/admin">Admin</a>
                <a href="/alimentadores">Alimentadores</a>
                <a href="/usuarios">Usuarios</a>
                <a href="/registrarse">Registrarse</a>
                <a href="/informacion">Información</a>
</div>

<div class="banner" style="padding:15px; text-align:center;">
<div class="banner-content">
<img src="https://image.flaticon.com/icons/svg/2927/2927929.svg" width="100" height="100">
<h1>Mis Cosas</h1>
<p>Página web con todas mis cosas</p>
</div>
</div>

{% if user.is_authenticated %}

	<p class="top-menu">Hola {{ user.username }} <small>(<a href="{% url 'logout_user' %}">Log out</a>)</small></p>


{% else %}

<button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Login</button>

<div id="id01" class="modal">
  
  <form class="modal-content animate" action="/login" method="POST">
    <div class="imgcontainer">
      <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
      <img src="https://www.w3schools.com/howto/img_avatar.png" height="33%"  alt="Avatar" class="avatar">
    </div>

    <div class="container">
<!--      <label for="uname"><b>Username</b></label>
      <input type="text" placeholder="Enter Username" name="uname" required>

      <label for="psw"><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="psw" required> -->
      {{ form.as_p }}
      {% csrf_token %}
      <button type="submit">Login</button>
      <label>
        <input type="checkbox" checked="checked" name="remember"> Remember me
      </label>
    </div>

    <div class="container" style="background-color:#f1f1f1">
      <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
      <span class="psw">Forgot <a href="#">password?</a></span>
    </div>
  </form>
</div>

{% endif  %}

<!--
<div class="page-header">

        {% if user.is_authenticated %}
            <a href="{% url 'principal_page' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <a href="{% url 'usuarios_page' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
            <p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'logout_user' %}">Log out</a>)</small></p>
 
        {% else %}
                {% if form.errors %}
                    <p>Your username and password didn't match. Please try again.</p>
                {% endif %}

            <h1>Iniciar sesión</h1>
            <form class="login" action="/login" method="POST">
                {{ form.as_p }}
                {% csrf_token %}
                <button type="submit">Login</button">
            </form>

            <a href="{% url 'login_user' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
        {% endif %}
 -->

</div>



    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>


<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>


<br>
<footer>
	Esta web utiliza material de Youtube y Wikipedia sin ningún fin 
	lucrativo y únicamente con fines educativos.
	<br>
	Copyright &copy; 2020
</footer>


</body>
</html>

mis_cosas/web_mis_cosas/templates/blog/item.html
{% extends 'blog/base.html' %}

{% block content %}

<h3> {{ item.titulo }} </h3>

{% if item.tipo == "youtube"  %}
<iframe width="560" height="315" src="https://www.youtube.com/embed/{{ item.id_video  }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
{% endif  %}

<h4>Link</h4>{{ item.enlace }}
<h4>Descripción</h4>{{ item.descripcion }}
<br><br>

<h2>Comentarios de este item:</h2>
	<br>
    {% for comentario in item.comentario_set.all %}
	<div class="comentario">
            <b>Comentario de <a href="">{{ comentario.autor }}</a>:</b>
		<div class="texto">
                	{{ comentario.texto|linebreaksbr }}
        	</div>
		<br>
        </div>
    {% endfor %}

{% if user.is_authenticated %}

        <b><p class="top-menu">Añade un comentario nuevo</p></b>

        <form action="" method="POST">{% csrf_token %}
                <input type="text" name="valor">
                <input type="submit" name="action" value="Comentar">
        </form>
<br>

        <b>Puntuación</b><br>
        Este item tiene <b>{{ puntuacion }}</b> puntos <br>
        <b>{{item.votos_pos}}</b> votos a favor | <b>{{item.votos_neg}}</b> votos en contra<br><br>


	<b>Votar el item</b>
        <form action="" method="POST">{% csrf_token %}
               Me gusta <input type="submit" name="voto" value="( + )">
               No me gusta<input type="submit" name="voto" value="( - )">
        </form>


{% endif %}



{% endblock %}

mis_cosas/web_mis_cosas/templates/blog/principal.html
{% extends 'blog/base.html' %}

{% block content %}

<form action="/?format=xml" method="GET">{% csrf_token  %}
<input type="submit" name="format" value="xml">Descarga fichero como XML
</form>
<form action="/?format=json" method="GET">{% csrf_token  %}
<input type="submit" name="format" value="json">Descarga fichero como JSON
</form>

	<br>
<h3>Elegir alimentador:</h3>
	<form action="" method="POST">{% csrf_token %}
		Elige un canal de Youtube (ID):
		<input type="text" name="valor">
		<input type="submit" name="action" value="VER_YT">
	</form>

        <form action="" method="POST">{% csrf_token %}
                Elige un artículo de Wikipedia (title):
                <input type="text" name="valor">
                <input type="submit" name="action" value="VER_WK">
        </form>
        <br>

        <h3>Lista de items más puntuados</h3>

		<table>
			<tr>
				<th>Item</th>
				<th>Página del Item</th>
				<th>Link</th>
                                <th>Votos+</th>
                                <th>Votos-</th>
	{% if user.is_authenticated %}
                                <th>+</th>
                                <th>-</th>
	{% endif %}
			</tr>
        {% for item in lista_items %}
			<tr>
				<th>{{ item.titulo }}</th>
				<th><a href="/item/{{ item.id_video  }}">[Página item]</a></th>
				<th><a href="{{ item.enlace }}">Link</a></th>
				<th>{{ item.votos_pos  }}</th>
				<th>{{ item.votos_neg  }}</th>
	{% if user.is_authenticated %}
                         <form action="/item/{{ item.id_video  }}" method="POST">{% csrf_token %}
                              <th><input type="submit" name="voto" value="( + )"></th>
                              <th><input type="submit" name="voto" value="( - )"></th>
                        </form>
	{% endif %}
			</tr>
<!--
            <div>
                <li>Item: {{ item.titulo }}<br>
		<a href="/item/{{ item.id_video  }}">[Página item]</a><br>
                <a href="{{ item.enlace }}">Link</a>
		</li><br>
            </div>
-->
        {% endfor %}
</table>


<br><br><br>
<h3>Lista de alimentadores elegidos</h3>

	<table>
                        <tr>
                                <th>Alimentador</th>
                                <th>Link</th>
                                <th>Items disponibles</th>
                                <th>Puntuación</th>
				<th>Elegir</th>
                                <th>Eliminar</th>
			</tr>

    {% for alimentador in lista_alimentadores %}
        {% if alimentador.elegido == True  %}
	<tr>
	        <th><a href="{% url 'alimentador_info' alim_id=alimentador.id_canal%}">{{ alimentador.titulo }}</th>
       		<th><a href="{{ alimentador.enlace }}">{{ alimentador.enlace }}</a></th>
        	<th>{{alimentador.item_set.count}}</th>
		<th>{{alimentador.puntuacion}}</th>
                 <form action="/alimentadores/{{alimentador.id_canal}}" method="POST">{% csrf_token %}
                          <th><input type="submit" name="elegir" value="Elegir"></th>
                          <th><input type="submit" name="elegir" value="Eliminar"></th>
                 </form>
        </tr>
        {% endif %}
    {% endfor %}
    </table>
<br><br>

{% if user.is_authenticated %}

<h3>Lista de últimos 5 items votados por {{user.username}}</h3>

        {% for voto in lista_votos %}
            <div>
                <p><a href="/item/{{ voto.item.id_video  }}">{{ voto.item }}</a></p>
            </div>
        {% endfor %}

{% endif %}



{% endblock %}

mis_cosas/web_mis_cosas/templates/blog/void.html
<html>
EMPTY
&
FAILURE
</html>